/* eslint-disable */
/* protocol buffer code generated by https://protip.dev */

import * as jspb from "google-protobuf"

import * as google_protobuf_timestamp_pb from 'google-protobuf/google/protobuf/timestamp_pb';

export class SayHelloRequest extends jspb.Message {
  getLanguage(): string;
  setLanguage(value: string): void;

  serializeBinary(): Uint8Array;
  toObject(includeInstance?: boolean): SayHelloRequest.AsObject;
  static toObject(includeInstance: boolean, msg: SayHelloRequest): SayHelloRequest.AsObject;
  static serializeBinaryToWriter(message: SayHelloRequest, writer: jspb.BinaryWriter): void;
  static deserializeBinary(bytes: Uint8Array): SayHelloRequest;
  static deserializeBinaryFromReader(message: SayHelloRequest, reader: jspb.BinaryReader): SayHelloRequest;
}

export namespace SayHelloRequest {
  export type AsObject = {
    language: string,
  }
}

export class SayHelloResponse extends jspb.Message {
  getHello(): string;
  setHello(value: string): void;

  serializeBinary(): Uint8Array;
  toObject(includeInstance?: boolean): SayHelloResponse.AsObject;
  static toObject(includeInstance: boolean, msg: SayHelloResponse): SayHelloResponse.AsObject;
  static serializeBinaryToWriter(message: SayHelloResponse, writer: jspb.BinaryWriter): void;
  static deserializeBinary(bytes: Uint8Array): SayHelloResponse;
  static deserializeBinaryFromReader(message: SayHelloResponse, reader: jspb.BinaryReader): SayHelloResponse;
}

export namespace SayHelloResponse {
  export type AsObject = {
    hello: string,
  }
}

export class CurrentTimeRequest extends jspb.Message {
  serializeBinary(): Uint8Array;
  toObject(includeInstance?: boolean): CurrentTimeRequest.AsObject;
  static toObject(includeInstance: boolean, msg: CurrentTimeRequest): CurrentTimeRequest.AsObject;
  static serializeBinaryToWriter(message: CurrentTimeRequest, writer: jspb.BinaryWriter): void;
  static deserializeBinary(bytes: Uint8Array): CurrentTimeRequest;
  static deserializeBinaryFromReader(message: CurrentTimeRequest, reader: jspb.BinaryReader): CurrentTimeRequest;
}

export namespace CurrentTimeRequest {
  export type AsObject = {
  }
}

export class CurrentTimeResponse extends jspb.Message {
  getCurrentTime(): google_protobuf_timestamp_pb.Timestamp | undefined;
  setCurrentTime(value?: google_protobuf_timestamp_pb.Timestamp): void;
  hasCurrentTime(): boolean;
  clearCurrentTime(): void;

  serializeBinary(): Uint8Array;
  toObject(includeInstance?: boolean): CurrentTimeResponse.AsObject;
  static toObject(includeInstance: boolean, msg: CurrentTimeResponse): CurrentTimeResponse.AsObject;
  static serializeBinaryToWriter(message: CurrentTimeResponse, writer: jspb.BinaryWriter): void;
  static deserializeBinary(bytes: Uint8Array): CurrentTimeResponse;
  static deserializeBinaryFromReader(message: CurrentTimeResponse, reader: jspb.BinaryReader): CurrentTimeResponse;
}

export namespace CurrentTimeResponse {
  export type AsObject = {
    currentTime?: google_protobuf_timestamp_pb.Timestamp.AsObject,
  }
}

