/* eslint-disable */
/* protocol buffer code generated by https://protip.dev */

/**
 * @fileoverview gRPC-Web generated client stub for protip.examples.helloworld
 * @enhanceable
 * @public
 */

// GENERATED CODE -- DO NOT EDIT!


import * as grpcWeb from 'grpc-web';

import * as google_protobuf_timestamp_pb from 'google-protobuf/google/protobuf/timestamp_pb';

import {
  CurrentTimeRequest,
  CurrentTimeResponse,
  SayHelloRequest,
  SayHelloResponse} from './helloworld_pb';

export class HelloWorldClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: string; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: string; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname;
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodInfoSayHello = new grpcWeb.AbstractClientBase.MethodInfo(
    SayHelloResponse,
    (request: SayHelloRequest) => {
      return request.serializeBinary();
    },
    SayHelloResponse.deserializeBinary
  );

  sayHello(
    request: SayHelloRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.Error,
               response: SayHelloResponse) => void) {
    return this.client_.rpcCall(
      this.hostname_ +
        '/protip.examples.helloworld.HelloWorld/SayHello',
      request,
      metadata || {},
      this.methodInfoSayHello,
      callback);
  }

  methodInfoCurrentTime = new grpcWeb.AbstractClientBase.MethodInfo(
    CurrentTimeResponse,
    (request: CurrentTimeRequest) => {
      return request.serializeBinary();
    },
    CurrentTimeResponse.deserializeBinary
  );

  currentTime(
    request: CurrentTimeRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.Error,
               response: CurrentTimeResponse) => void) {
    return this.client_.rpcCall(
      this.hostname_ +
        '/protip.examples.helloworld.HelloWorld/CurrentTime',
      request,
      metadata || {},
      this.methodInfoCurrentTime,
      callback);
  }

}

